name: Keep the versions up-to-date

on:
  release:
    types: [published, edited]

permissions:
  contents: write

jobs:
  run-tag-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: Actions-R-Us/actions-tagger@330ddfac760021349fef7ff62b372f2f691c20fb # latest
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          publish_latest_tag: 'true'
